name: Java CI with Maven
on:
  push: 
  pull_request:
    types: [opened ,created ,reopened]
    branches:
      - '**'
      - '!**_skip'

    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - run: echo "github.ref by  ${{ github.ref }} "
      if: contains(github.ref, '_skip')
    - run: echo "github.event_name by  ${{ github.event_name }} "
    #- run: echo "github.event.action by  ${{ github.event.action }} "
    - run: echo "github.event.label.name  by  ${{ github.event.label.name  }} "
    - run: echo "github.event.pull_request.labels.*.name  by  ${{ github.event.pull_request.labels.*.name }} "
    - run: echo "runner.os on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo " branch is ${{ github.ref }} and ${{github.head_ref}} ${{github.sha}}your repository is ${{ github.repository }}."

    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "github.workspace The ${{ github.repository }} "
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    
    - run: echo ""	
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Checkout
      uses: actions/checkout@master

    #- name: Build WSC
    #  uses: cuikang1986/wsc@master
      
    - name: Build WSC2
      uses: actions/checkout@v2
      with:
        repository: cuikang1986/wsc
        ref: master
        path: ~/.m2
    - name: install with Maven
      run: mvn install
      
      
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-
            
  #  - name: Test with Maven
    #  run: mvn -B test -Dmaven.test.skip=false

  #  - name: Build with Maven
  #    run: mvn -B package --file pom.xml
