name: Java CI with Maven
on:
  push:
  workflow_dispatch:
  pull_request: 
    types: [open, reopened, synchronized]
env:
 B2: 'b2'
 B3: "b3" 
jobs:
  build:
    if: "!contains(github.event.pull_request.title, '[skip]')"
    runs-on: ubuntu-latest

    steps:
    - run: echo "github.event.pull_request.title by  ${{ github.event.pull_request.title }} "
      if: "!contains(github.event.pull_request.title, '[skip]')"
    - run: echo "github.ref by  ${{ github.ref }} "
    - run: echo "github.head_ref by  ${{ github.head_ref }} "
    #- run: echo "github.event.action by  ${{ github.event.action }} "
    - run: echo "github.event.label.name  by  ${{ github.event.label.name  }} "
    - run: echo "github.event.pull_request.labels.*.name  by  ${{ github.event.pull_request.labels.*.name }} "
    - run: echo "runner.os on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo " branch is ${{ github.ref }} and ${{github.head_ref}} ${{github.sha}}your repository is ${{ github.repository }}."

    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "github.workspace The ${{ github.repository }} "
   
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
   
    #- run: echo ${{github.event.workflow_dispatch.labels[0].name}}
    - run: echo ${{toJson(github.event.pull_request.labels.*.name)}}
    #- run: echo ${{github.event.pull_request.labels[0].name}}
    
    - run: echo 1= ${{contains(github.event.pull_request.labels.*.name, 'b1')}}
    - run: echo 2= ${{contains(github.event.pull_request.labels.*.name, 'b2')}}
    - run: echo 3= ${{contains(github.event.pull_request.labels.*.name, 'b3')}}
    
    
    - name: Checkout
      if: contains(github.event.pull_request.labels.*.name, 'b1')
      uses: actions/checkout@master
    
    - name: Set up JDK 11
      if: ${{contains(github.event.pull_request.labels.*.name,  env.B2) }}
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven


    - name: Build WSC2
      if: ${{contains(github.event.pull_request.labels.*.name,  env.B3)}}
      uses: actions/checkout@v2
      with:
        repository: cuikang1986/wsc
        ref: master
        path: ~/.m2
        
        
    #- name: install with Maven
    #  run: mvn install
      
      
   # - name: Cache local Maven repository
   #   uses: actions/cache@v2
   #   with:
  #      path: ~/.m2/repository
   #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
   #     restore-keys: |
    #        ${{ runner.os }}-maven-
            
  #  - name: Test with Maven
    #  run: mvn -B test -Dmaven.test.skip=false

  #  - name: Build with Maven
  #    run: mvn -B package --file pom.xml
