# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven


on:
  pull_request:
    types: [opened ,created ,reopened]
    branches: 
      - '**'
      - '!**skip'
    
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'octo-team'}}
    steps:
      - run: echo 'A review from octo-team was requested'
      
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "github.event_name by a ${{ github.event_name }} event."
    - run: echo "runner.os on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo " branch is ${{ github.ref }} and ${{github.head_ref}} ${{github.sha}}your repository is ${{ github.repository }}."
    
    
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "github.workspace The ${{ github.repository }} "
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    
    
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Test with Maven
      run: mvn -B test -Dmaven.test.skip=false

    - name: Build with Maven
      run: mvn -B package --file pom.xml
